import { generateText, stepCountIs } from "ai";
import { getLanguageModel, DEFAULT_MODEL, InferenceError, parseModelSpec, buildThinkingOptions, buildSafetyOptions, modelSupportsTools, recordNoToolModel, isToolsNotSupportedError } from "./models";
import { debug, error } from "../logger";
import {
  type EvaluatedEntity,
  type MessageContext,
  normalizeMessagesForProvider,
} from "./context";
import { preparePromptContext } from "./prompt";
import { resolveAttachmentMarkers } from "./attachments";
import { getEntity } from "../db/entities";
import { createTools } from "./tools";
import { stripNamePrefix, parseNamePrefixResponse, type EntityResponse } from "./parsing";

// =============================================================================
// Types
// =============================================================================

export interface GeneratedFile {
  data: Uint8Array;
  mediaType: string; // e.g. "image/png"
}

export interface ResponseResult {
  response: string;
  files?: GeneratedFile[];
  entityResponses?: EntityResponse[];
  factsAdded: number;
  factsUpdated: number;
  factsRemoved: number;
  memoriesSaved: number;
  memoriesUpdated: number;
  memoriesRemoved: number;
  /** Set to the model spec if tools were auto-disabled for this model during this call */
  toolsAutoDisabledForModel?: string;
}

// =============================================================================
// Main Handler
// =============================================================================

export async function handleMessage(ctx: MessageContext): Promise<ResponseResult | null> {
  const { channelId, guildId, userId, isMentioned, respondingEntities } = ctx;

  const evaluated: EvaluatedEntity[] = respondingEntities ?? [];

  // Prepare prompt context (expand refs, resolve user entity, build prompt)
  const { systemPrompt, messages: llmMessages, nonce, other, contextExpr } = preparePromptContext(
    evaluated, channelId, guildId, userId, ctx.entityMemories,
  );

  // Decide whether to respond
  const shouldRespond = isMentioned || evaluated.length > 0 || other.length > 0;
  if (!shouldRespond) {
    debug("Not responding - not mentioned and no entities");
    return null;
  }

  debug("Calling LLM", {
    respondingEntities: evaluated.map(e => e.name),
    otherEntities: other.map(e => e.name),
    contextExpr,
    messageCount: llmMessages.length,
  });

  // Track tool usage
  let factsAdded = 0;
  let factsUpdated = 0;
  let factsRemoved = 0;
  let memoriesSaved = 0;
  let memoriesUpdated = 0;
  let memoriesRemoved = 0;
  let skipResponse = false;

  const modelSpec = evaluated[0]?.modelSpec ?? DEFAULT_MODEL;
  const { providerName, modelName } = parseModelSpec(modelSpec);
  const thinkingLevel = evaluated[0]?.thinkingLevel;
  const contentFilters = evaluated[0]?.contentFilters ?? [];
  const imageModelSpec = evaluated[0]?.imageModelSpec ?? null;

  try {
    const model = getLanguageModel(modelSpec);
    let toolsAutoDisabledForModel: string | undefined;

    // Resolve attachment markers (HATT → ImagePart / FilePart / text fallback)
    const entityId = evaluated[0]?.id ?? 0;
    const ownerId = entityId ? (getEntity(entityId)?.owned_by ?? "") : "";
    const resolvedMessages = await resolveAttachmentMarkers(llmMessages, nonce, providerName, entityId, ownerId);

    // Normalize messages for provider-specific restrictions (e.g., Google doesn't have system role)
    const normalizedMessages = normalizeMessagesForProvider(resolvedMessages, providerName);

    const thinkingOptions = buildThinkingOptions(providerName, modelName, thinkingLevel);
    const safetyOptions = buildSafetyOptions(providerName, contentFilters);
    const providerOptions = (thinkingOptions || safetyOptions)
      ? { ...thinkingOptions, ...safetyOptions }
      : undefined;

    // Sidecar: collect images generated by the generate_image tool
    const sidecarFiles: GeneratedFile[] = [];
    const imageOptions = imageModelSpec
      ? { imageModelSpec, onImage: (f: GeneratedFile) => sidecarFiles.push(f) }
      : undefined;

    const callOptions = {
      model,
      system: systemPrompt || undefined,
      messages: normalizedMessages,
      providerOptions,
      stopWhen: stepCountIs(5), // Allow up to 5 tool call rounds
      onStepFinish: ({ toolCalls }: { toolCalls?: { toolName: string }[] }) => {
        for (const call of toolCalls ?? []) {
          if (call.toolName === "add_fact") factsAdded++;
          if (call.toolName === "update_fact") factsUpdated++;
          if (call.toolName === "remove_fact") factsRemoved++;
          if (call.toolName === "save_memory") memoriesSaved++;
          if (call.toolName === "update_memory") memoriesUpdated++;
          if (call.toolName === "remove_memory") memoriesRemoved++;
          if (call.toolName === "skip_response") skipResponse = true;
        }
      },
    };

    let result;
    if (modelSupportsTools(modelSpec)) {
      try {
        result = await generateText({ ...callOptions, tools: createTools(channelId, guildId, ctx.triggerEntityFn, imageOptions, evaluated[0]?.id, evaluated[0]?.ownedBy) });
      } catch (toolErr) {
        if (isToolsNotSupportedError(toolErr)) {
          // Model doesn't support tool calls — record, retry without tools
          const isNew = recordNoToolModel(modelSpec);
          if (isNew) toolsAutoDisabledForModel = modelSpec;
          result = await generateText(callOptions);
        } else {
          throw toolErr;
        }
      }
    } else {
      result = await generateText(callOptions);
    }

    debug("LLM response", {
      text: result.text,
      factsAdded,
      factsUpdated,
      factsRemoved,
      memoriesSaved,
      memoriesUpdated,
      memoriesRemoved,
    });

    // Collect generated image files (inline from model) + sidecar (from generate_image tool)
    const generatedFiles: GeneratedFile[] = [
      ...(result.files ?? [])
        .filter(f => f.mediaType.startsWith("image/"))
        .map(f => ({ data: f.uint8Array, mediaType: f.mediaType })),
      ...sidecarFiles,
    ];

    // Check if LLM called skip_response tool
    if (skipResponse) {
      debug("LLM called skip_response - no response");
      return null;
    }

    // Check for <none/> or "none" sentinel (LLM decided none should respond)
    const trimmedText = result.text.trim().toLowerCase();
    if (trimmedText === "<none/>" || trimmedText === "none") {
      debug("LLM returned none sentinel - no response");
      return null;
    }

    // Empty/whitespace-only response is an error unless the model returned image files
    if (!trimmedText && generatedFiles.length === 0) {
      throw new InferenceError("Empty response from model", modelSpec);
    }

    // Strip "Name:" prefix from single-entity responses
    let responseText = result.text;
    if (evaluated.length === 1) {
      responseText = stripNamePrefix(responseText, evaluated[0].name);
    }

    // Parse multi-entity response (skip if any entity has $freeform)
    const isFreeform = evaluated.some(e => e.isFreeform);
    const entityResponses = isFreeform ? undefined
      : parseNamePrefixResponse(responseText, evaluated);

    return {
      response: responseText,
      files: generatedFiles.length > 0 ? generatedFiles : undefined,
      entityResponses,
      factsAdded,
      factsUpdated,
      factsRemoved,
      memoriesSaved,
      memoriesUpdated,
      memoriesRemoved,
      toolsAutoDisabledForModel,
    };
  } catch (err) {
    error("LLM error", err);
    throw new InferenceError(
      err instanceof Error ? err.message : String(err),
      modelSpec,
      err,
    );
  }
}

